version: '3.0'

services:
  redis:
    image: redis:latest
    container_name: redis_rate_limiter
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis_init:
    image: redis:latest
    depends_on:
      - redis
    entrypoint: [ "sh", "-c", "
      until redis-cli -h redis ping | grep PONG; do sleep 1; done;
      echo 'Configurando rate limiters para a aplicação (DB 0)...'; 
      redis-cli -h redis -n 4 hset rate_limit:192.168.1.1 limit '5' time_block '60';
      redis-cli -h redis -n 0 hset rate_limit:api123 limit '100' time_block '300';
      echo 'Configurando rate limiters para testes (DB 4)...'; 
      redis-cli -h redis -n 4 hset rate_limit:192.168.1.1 limit '5' time_block '15';
      redis-cli -h redis -n 4 hset rate_limit:api123 limit '10' time_block '10';"
    ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - redis_init

  test:
    image: golang:latest
    container_name: test
    restart: no
    command: ["sh", "-c", "go test ./... -v"]
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - redis_init

volumes:
  redis_data: